baseURL = "https://jarry-hu.github.io/blog/"
languageCode = "en-us"
title = "Jarry's Blog"
theme = "PaperMod"

[params]
  # Enable dark mode
  defaultTheme = "auto"
  
  # Enable search
  enableSearch = true
  
  # Enable table of contents
  ShowToc = true
  
  # Show reading time
  ShowReadingTime = true
  
  # Show post sharing buttons
  ShowShareButtons = true
  
  # Show code copy buttons
  ShowCodeCopyButtons = true

  # Date format
  dateFormat = "2006-01-02"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight =5

  [[menu.main]]
    identifier = "invest"
    name = "Invest"
    url = "/invest/"
    weight = 7

  [[menu.main]]
    identifier = "daily"
    name = "Daily"
    url = "/daily/"
    weight = 10
    
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 15
    
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 20
    
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

[outputs]
  section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 添加忽略日志配置，避免警告
ignoreLogs = ['warning-goldmark-raw-html']
